### ISSUE TITLE
Server Side Code Example

### ISSUE THREAD

**Issue by sinaone1** [HavenDV/H.Socket.IO#20]
Hello
Your code works very well but the problem is I'm working with nodejs and I think my code has problem because it gives this error when I try to connect to that :

> ExceptionOccurred: System.Net.WebSockets.WebSocketException (0x83760002): Invalid data format for the specific protocol operation
   at System.Net.WebSockets.WebSocketProtocolComponent.WebSocketGetAction(WebSocketBase webSocket, ActionQueue actionQueue, Buffer[] dataBuffers, UInt32& dataBufferCount, Action& action, BufferType& bufferType, IntPtr& actionContext)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at H.WebSockets.WebSocketClient.<ReceiveAsync>d__47.MoveNext()
ExceptionOccurred: System.Net.WebSockets.WebSocketException (0x83760002): Invalid data format for the specific protocol operation
   at System.Net.WebSockets.WebSocketProtocolComponent.WebSocketGetAction(WebSocketBase webSocket, ActionQueue actionQueue, Buffer[] dataBuffers, UInt32& dataBufferCount, Action& action, BufferType& bufferType, IntPtr& actionContext)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at H.WebSockets.WebSocketClient.<ReceiveAsync>d__47.MoveNext()

I attached my server side code and you could check it
Thank you
[app.zip](https://github.com/HavenDV/H.Socket.IO/files/7013450/app.zip)

**Comment by HavenDV** [comment]
Hello. I will check it(approx 30 August, I have a trip now)

**Comment by sinaone1** [comment]
> Hello. I will check it(approx 30 August, I have a trip now)

Thank you

**Comment by Andrew-Gee** [comment]
+1
